Remove one additional access to google stuff in shaded curator package.
elek/hadoop-ozone pull request #11
Opened 2020-04-07 16:05 UTC by fapifta

## What changes were proposed in this pull request?

I found one more use of curator, it seems that in one of the tests, we are using something shaded into it.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3353

## How was this patch tested?
local build.

2020-04-08 08:29 UTC, adoroszlai requested changes
Nice catch @fapifta for the import from shaded package.

2020-04-08 08:29 UTC, adoroszlai commented on hadoop-hdds/container-service/src/test/java/org/apache/hadoop/ozone/container/common/volume/TestVolumeSetDiskChecks.java
> +import org.apache.commons.io.FileUtils;
Can we avoid moving imports back and forth? :)

2020-04-15 18:53 UTC, adoroszlai commented
This is obsoleted by apache/hadoop-ozone#818.

2020-04-15 19:47 UTC, fapifta commented
Closing this one.

2020-04-15 19:47 UTC, closed without merging